--brush generated by [Zax37] in BrushMaker (by Zax37) 11.7.2011
gameID = wmCLAW
layerName = "ACTION"
levelID = 4
brushName_PL = "Drabina"
brushName = "Ladder"
brushIcon = 181

function cbBrushPlaced(plPlane, iX, iY)
if wmGetTile(plPlane, iX, iY)==183 and wmGetTile(plPlane, iX, iY+1)==181 then wmPlaceTile(plPlane, iX, iY, 182) wmPlaceTile(plPlane, iX, iY+1, 182)
elseif wmGetTile(plPlane, iX, iY-1)==183 and wmGetTile(plPlane, iX, iY)==181 then wmPlaceTile(plPlane, iX, iY-1, 182) wmPlaceTile(plPlane, iX, iY, 182)
elseif wmGetTile(plPlane, iX, iY+1)==181 then wmPlaceTile(plPlane, iX, iY, 181) wmPlaceTile(plPlane, iX, iY+1, 182)
elseif wmGetTile(plPlane, iX, iY-1)==183 and wmGetTile(plPlane, iX, iY+1)==181 then wmPlaceTile(plPlane, iX, iY-1, 182) wmPlaceTile(plPlane, iX, iY, 182) wmPlaceTile(plPlane, iX, iY+1, 182)
elseif wmGetTile(plPlane, iX, iY-1)==183 then wmPlaceTile(plPlane, iX, iY-1, 182) wmPlaceTile(plPlane, iX, iY, 183)
elseif wmGetTile(plPlane, iX, iY-1)==182 and wmGetTile(plPlane, iX, iY+1)==182 then wmPlaceTile(plPlane, iX, iY-1, 182) wmPlaceTile(plPlane, iX, iY, 182) wmPlaceTile(plPlane, iX, iY+1, 182)
elseif wmGetTile(plPlane, iX, iY)==182 then wmPlaceTile(plPlane, iX, iY, 182)
elseif wmGetTile(plPlane, iX, iY)==183 then wmPlaceTile(plPlane, iX, iY, 182) wmPlaceTile(plPlane, iX, iY+1, 183)
elseif wmGetTile(plPlane, iX, iY)==181 then wmPlaceTile(plPlane, iX, iY, 181)
else wmPlaceTile(plPlane, iX, iY, 181) wmPlaceTile(plPlane, iX, iY+1, 183)
end
end
